### ISSUE TITLE
云盘上传无限失败

### ISSUE THREAD

**Issue by vbnetvbnet** [ydq/netease-cloud-disk-music-upload#1]
到了晚上又可以用了，可能是网络不稳定吧..
Close

**Comment by ydq** [comment]
> 到了晚上又可以用了，可能是网络不稳定吧.. Close

其实写这个插件的时候我就发现这个问题了，可能是网易云的上传服务不稳定或者有其它不为人知的原因，确实会有段时间内上传失败的问题。所以上传中的每一个步骤失败了，都在代码中做了一次重试，而且失败后的提示也是手动重试几次没准会有惊喜😂

**Comment by vbnetvbnet** [comment]
> > 到了晚上又可以用了，可能是网络不稳定吧.. Close
> 
> 其实写这个插件的时候我就发现这个问题了，可能是网易云的上传服务不稳定或者有其它不为人知的原因，确实会有段时间内上传失败的问题。所以上传中的每一个步骤失败了，都在代码中做了一次重试，而且失败后的提示也是手动重试几次没准会有惊喜😂

真心不错👍👍

**Comment by hoochanlon** [comment]
大佬，请教一个题外话的问题：这种类别的issue是怎么设置的？我一般关闭的issue基本上都是紫色的。

<img width="975" alt="image" src="https://user-images.githubusercontent.com/35732922/220500284-f06c0855-81c6-4e25-89f0-78e9e82739cf.png">
