### ISSUE TITLE
上传发生了一点问题，正在自动重试...

### ISSUE THREAD

**Issue by mrzhangs520** [ydq/netease-cloud-disk-music-upload#11]
![iShot_2023-12-05_16 33 38](https://github.com/ydq/netease-cloud-disk-music-upload/assets/48706034/754e5b88-8f24-40f6-9d5d-e94f40869aea)

**Comment by ydq** [comment]
上个版本有点bug，导致不会自动重试，另外现阶段的自动重试成功率也不高，想了另外一个方案 可以看看 https://github.com/ydq/netease-cloud-disk-music-upload/issues/8 ，一直没有时间弄，如果你着急的话，可以尝试用 ffmpeg 或者一些转码工具转一次码 改变文件的hash再尝试，或者等一段时间再试说不定就好了
