### ISSUE TITLE
感谢作者，不知道是不是可以直接播放或者操作歌单的api

### ISSUE THREAD

**Issue by kelegeek** [ydq/netease-cloud-disk-music-upload#12]

**Comment by ydq** [comment]
好像有 歌单相关的API，但是 https://github.com/Binaryify/NeteaseCloudMusicApi 这个仓库貌似被 和谐 了，没文档了，而且歌单的操作和播放各端的网易云官方app都有很好的支持吧？

**Comment by kelegeek** [comment]
因为不是很想开黑胶。要是能单独做个桌面版本 只依赖网盘做播放器也是可以的

**Comment by ydq** [comment]
> 因为不是很想开黑胶。要是能单独做个桌面版本 只依赖网盘做播放器也是可以的

https://github.com/Dreamkaka/NeteaseCloudMusicApi  这个看commit 应该是一个比较完整的 fork，而且他部署的 pages 服务还可以访问，如果你有需要可以参考一下，感觉网易云这么搞下去，人心惶惶啊，白瞎了我好几年的 黑胶VIP7（虽然都是淘宝88送的）😭
