### ISSUE TITLE
上传歌曲问题

### ISSUE THREAD

**Issue by 0xc0ee** [ydq/netease-cloud-disk-music-upload#13]
上传页面新增歌曲重新排序后删除个别歌曲不准确，还有能加一下全部上传歌曲时可以按顺序依次上传功能吗？（不批量一起）

**Comment by ydq** [comment]
> 上传页面新增歌曲重新排序后删除个别歌曲不准确，还有能加一下全部上传歌曲时可以按顺序依次上传功能吗？（不批量一起）

我懂了，我先研究一下，因为用的是 antdv 的框架，目前的表格排序是它内部的排序，删除不准确的应该也是这个问题引起的一个 bug，我得研究一下怎么弄

**Comment by ydq** [comment]
试试 2.1
