### ISSUE TITLE
[Feature request] 歌曲匹配纠偏

### ISSUE THREAD

**Issue by lixvbnet** [ydq/netease-cloud-disk-music-upload#2]
可以加入歌曲匹配纠偏功能吗？支持手动输入正确的歌曲ID，类似于s337443501/NeteaseMusicCloudMatch（只能windows用，不太方便）

**Comment by ydq** [comment]
可以，这两天抽空，下一个版本就加上

**Comment by ydq** [comment]
已经提交应用商店审核了，根据之前的情况，预估一两天就可以上架自动更新了，如果急迫的话可以自己本地打包

**Comment by lixvbnet** [comment]
神速🚀 谢谢！

**Comment by ydq** [comment]
@lixvbnet  Chrome 应用商店已经审核通过并上架了
