### ISSUE TITLE
支持，大赞

### ISSUE THREAD

**Issue by eryajf** [ydq/netease-cloud-disk-music-upload#4]
此issue没有疑问，单纯是为了感谢，在Mac上折腾这个功能，用了各种曲线救国的方案，

我还专门开了个贴（见 [讨论： 2023 年了，你的 Mac 是如何解决往网易音乐云的云盘上传歌曲的？](https://v2ex.com/t/918049#reply18)）征求方案，都没有遇到理想的。

要么不理想，要么不好用，这个插件简单易用，超级感谢。

---

最后有个小小建议：建议项目的README里也加上预览图，这样如果有人通过github看到这个项目，能比较直观的看到效果。

**Comment by ydq** [comment]
> 此issue没有疑问，单纯是为了感谢，在Mac上折腾这个功能，用了各种曲线救国的方案，
> 
> 我还专门开了个贴（见 [讨论： 2023 年了，你的 Mac 是如何解决往网易音乐云的云盘上传歌曲的？](https://v2ex.com/t/918049#reply18)）征求方案，都没有遇到理想的。
> 
> 要么不理想，要么不好用，这个插件简单易用，超级感谢。
> 
> 最后有个小小建议：建议项目的README里也加上预览图，这样如果有人通过github看到这个项目，能比较直观的看到效果。

哈哈  谢谢支持，之前README 里面是有放截图的，但是因为改了几版，现在的界面和最早的截图都不太一样了，每次截图修图比较麻烦（PS：连应用商店的图都懒得换了，哈哈哈），所以索性就都去掉了

**Comment by eryajf** [comment]
好的
