### ISSUE TITLE
谢谢，非常实用。没找到你邮箱，发个感谢issue

### ISSUE THREAD

**Issue by hoochanlon** [ydq/netease-cloud-disk-music-upload#5]
在感谢的同时，我想请教大佬一个题外话的问题，就是这种类别的issue是怎么设置的？我一般关闭的issue基本上都是紫色的。这个issue似乎能屏蔽掉之后关于下面的issue发文。这样的话，之后我的repo也能用上。

<img width="575" alt="image" src="https://user-images.githubusercontent.com/35732922/220500284-f06c0855-81c6-4e25-89f0-78e9e82739cf.png">

**Comment by ydq** [comment]
也许你要的是这个……

<img width="906" alt="image" src="https://user-images.githubusercontent.com/8097340/220809488-c29a5a14-39f7-4a0f-a98f-064149e25e4b.png">
