### ISSUE TITLE
学习请教

### ISSUE THREAD

**Issue by Fupeng-Chu** [ydq/netease-cloud-disk-music-upload#6]
大佬你好：

我每天需要登录不同的网易云账号往云盘上传歌曲（设备为win10网易云客户端），但是如果登录的号比较多，就会被判定为风险设备，就没法登录别的号了，请问有解决办法吗？

非常期待大佬的回复！
wechat：cfpwym

**Comment by ydq** [comment]
我在开发测试的时候 似乎也遇到过类似的问题，频繁的扫码登录/注销直接封了我几天

客户端的风控策略我不太清楚，但是如果是使用这个浏览器插件有类似的需求的话，我觉得我可以尝试一下，利用 chrome cookie 的 api，获取当前登录的账号，将网易云的所有cookie 直接存储下来，需要恢复某个账号的时候直接恢复所有的cookie即可，这样应该可以做到支持多账号不注销的切换，但是不能保证一定可行，毕竟有可能还有其它风控。

如果你临时想要处理的话，感觉只能下载多个不同的 Chromium 系浏览器（如 chrome + edge + 其它一些 支持chrome扩展的浏览器 一起配合使用）来降低频繁登录触发风控的风险

**Comment by Fupeng-Chu** [comment]
大佬，这个插件是不是不支持以下两个功能：
1 文件夹上传
2 把待上传区的所有音频一键批量上传

**Comment by ydq** [comment]
我不是啥大佬哈～  我也只是一个后端开发，会一点前端皮毛而已🤪

**是的，你说的两个当前不支持**

#### 关于第1点： 文件夹上传 
文件夹上传  其实说白了就是 【选择文件】的时候允许选择文件夹 以及 【拖放文件】时支持拖放文件夹
- 【选择文件】如果支持选择文件夹，会导致不支持多选文件（当前是支持多选文件的），这个是浏览器的限制，二者选其一，经过取舍之后觉得多选文件的场景可能会更实用一些
- 【拖放文件】如果支持拖放文件夹的话，当时好像考虑要判断递归（文件夹套文件夹的情况，边界情况太多了），或者可能有其它原因（可能是我没研究明白），所以就放弃了


#### 关于第2点： 把待上传区的所有音频一键批量上传
目前对于网页来说，能做的就是一键点击自动化的按顺序上传，早先尝试过使用 service-worker 想后台多线程的方式计算MD5和上传，但是好像是内存占用比较大，而且也比较卡，或是其它原因，具体原因我忘了，就放弃了。回头我可以再试试自动化的单线程批量上传列表里面的内容。

PS：多账号的支持 目前有点眉目了

**Comment by ydq** [comment]
多账号支持 开发完成了   粗略的测试了下 没发现啥大的问题

- <img width="400" alt="image" src="https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/cfbab04b-feb8-42b2-bac6-748b886956ec">


- <img width="375" alt="image" src="https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/157a1bdc-b14e-451d-9da1-1ffe7463d44d">


- <img width="416" alt="image" src="https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/f26c79fa-5d9c-40fa-aabb-35aa5fe140f0">

**Comment by ydq** [comment]
@Fupeng-Chu  Chrome 应用商店已经审核通过

**Comment by Fupeng-Chu** [comment]
太牛了！
