### ISSUE TITLE
[Feature request] firefox addon release

### ISSUE THREAD

**Issue by AgFlore** [ydq/netease-cloud-disk-music-upload#7]
Firefox users can no longer install `.crx` extensions as `Chrome-Store-Foxified` has been discontinued since 2021. Would be very grateful if you would maintain an authorized release of this extension in the firefox extension store.

How-to:
https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

**Comment by ydq** [comment]
已提交商店审核了，不确定啥时候能过

**Comment by ydq** [comment]
@AgFlore  已经审核通过，可以下载了 https://addons.mozilla.org/zh-CN/firefox/addon/%E7%BD%91%E6%98%93%E4%BA%91%E9%9F%B3%E4%B9%90%E4%BA%91%E7%9B%98%E7%AE%A1%E7%90%86/
