### ISSUE TITLE
上传失败

### ISSUE THREAD

**Issue by Justwannasleep** [ydq/netease-cloud-disk-music-upload#8]
![image](https://github.com/ydq/netease-cloud-disk-music-upload/assets/39079024/2cf032fe-2288-475c-9a70-494fcb6bf0c0)
上传失败，但是接口响应均为200 .

**Comment by ydq** [comment]
嗯，网易云的接口一直都有这个问题
另外判断是否成功不是看的 http 的 code ，而是看响应体 json 里面的code
一般来说，换个时间段或者多试几次可能就莫名其妙的成功了，不妨试试看～

**Comment by ZeSui** [comment]
最近的上传云盘成功率非常低， 不知道为啥，貌似都没有，但是我通过手机其他方式打开又可以导入

**Comment by ydq** [comment]
@ZeSui  目前都是利用网友整理的一些已知官方接口来做上传的，网易云盘的完整上传流程是：

1. 本地文件计算md5
2. 检查是否需要上传
3. 如果需要上传则上传文件（文件网盘）
4. 编辑文件信息 
5. 保存到云盘（播放列表）

1→2→3→4→5 或者是  1→2→4→5 

我自己试验了一下
- 如果是从 如 QQ 音乐 下载然后直接 unlock 出来的 flac 等版权音乐，不经过任何转码，第【2】步网易云校验不用上传（第【2】步会返回一个网盘的文件访问地址，但是我尝试访问返回的地址却显示文件不存在，正常自己上传的话是可以访问的），然后最后一步【5】保存到网盘的时候报错 523 的错误导致失败
- 如果音乐是我自己二次转码过的（改变了文件的hash），基本上都会成功（但是也测试次数多了也可能会失败，即从我的网盘删除音乐，然后重新上传，多次操作，有一定的概率也会报错）
> 猜测可能与版权校验之类的有关原因 或者 【文件网盘】中判定虽然不用上传，但是真实的文件不存在了，导致【5】保存失败

但是当我尝试用 js 强制往文件后面追加一个空的字节，破坏原来的hash，可以正常上传并保存成功，也能播放了

回头我看看尝试加个配置开关，普通操作失败之后允许插件修改用户上传的文件，提升上传的成功率

**Comment by ZeSui** [comment]
破坏hash应该是可以起到效果，我下了一个转换工具，重新生成一份文件之后就成功了
当然，如果插件本身可以支持的话，可以省去用户更多的操作

**Comment by ydq** [comment]
@ZeSui  @mrzhangs520   抱歉打扰一下哈，方便提供一些上传失败的样例文件给我么，最近按照这个思路改了改，但是我这边测试了好多文件，都是一次性就成功了，不太确定功能是否OK

**Comment by ydq** [comment]
最新版已经提交应用商店，新的自动重试功能本地测试成功率大幅提升
