### ISSUE TITLE
支持移动设备

### ISSUE THREAD

**Issue by Goojoe** [ydq/netease-cloud-disk-music-upload#9]
请支持一下移动设备，kiwibrowser可以装扩展，这样纠正歌曲信息会方便很多

**Comment by ydq** [comment]
天呐，为啥会有这么精致的需求
感觉适配手机UI的话是不是不需要上传功能，只需要能读取列表（能下载、能删除）、纠正歌曲信息 就够了

**Comment by Goojoe** [comment]
上传也需要呀，app版权歌曲不给上传

**Comment by ydq** [comment]
> 上传也需要呀，app版权歌曲不给上传

目前应该是走的一样的接口，如果app上传不了，那插件可能也不一定能上传

另外因为插件本身是为 mac（pc）用户写的，所以没考虑过手机用户，不过我稍微调整了一下兼容性，然后特意找了个安卓手机试了下 你说的 kiwibrowser，理论上现在应用商店的版本也是可以正常使用的，只是字体可能会特别小，手指缩放一下 或者 横屏 就能使用了，我还试了下另外一款 “狐猴浏览器” 也支持的还不错

**Comment by Goojoe** [comment]
嗯，我知道扩展能用，就是不太好用

我试了下，版权歌曲确实不能上传。我在pc是用ffmpeg复制流改hash的，所以不做上传应该也行吧

另外狐猴是基于kiwibrowser二改的

**Comment by ydq** [comment]
添加了一个 lite 版本，回头我找个安卓手机重新测试一下，没问题的话再上传应用商店

---
|列表|上传|匹配|删除|
|---|---|---|---|
|![list](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/eb80e035-10b7-4257-b292-73d2f65fa424)|![upload](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/2b1fd275-30a1-4e80-a0f7-b403a86e28fc)|![match](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/94b696c4-aec0-4c9b-a37d-4c7631a5085a)|![delete](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/ea25d307-6515-4028-8b99-df067f641542)|

**Comment by ydq** [comment]
@Goojoe  火狐应用商店已经上线，也支持了最新的 Firefox for Android （119+），Chrome 和 Edge 还在审核

|应用商店|安装|启动|列表|
|---|---|---|---|
|![store](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/e52409f9-e6b6-4b3b-acfb-d8e9227b422e)|![ext](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/64cafe29-e026-4e6b-9918-3584a9d8e012)|![launch](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/10f19708-22bb-46cc-94a7-718b548dfc6e)|![list](https://github.com/ydq/netease-cloud-disk-music-upload/assets/8097340/6a5f9867-0bf3-4659-9832-52d9c61bed77)|

**Comment by Goojoe** [comment]
非常感谢
